### ISSUE TITLE
Question: why do you have a pool of reverse proxies?

### ISSUE THREAD

**Issue by danielfireman** [yeqown/fasthttp-reverse-proxy#1]
Hi there! Good evening!

I was taking a look at your reverse proxy implementation and noticed that you're trying to pool them. That made me really curious as the fasthttp library already has a pool of connections per client.  What are your thoughts about it?

Thanks a lot!

**Comment by yeqown** [comment]
I'm sorry to reply so late, i didn't receive any notice about the this issue, sorry~
for the question, I do not read fasthttp's code in detail while I coding this, that caused the duplicated work , I'll clean my code.

thanks for your remind a lot!

**Comment by yeqown** [comment]
@danielfireman
