### ISSUE TITLE
Logger returns 2 values

### ISSUE THREAD

**Issue by abhijitgujar86** [yeqown/fasthttp-reverse-proxy#14]
# github.com/yeqown/fasthttp-reverse-proxy
/home/abhijit/go/src/github.com/yeqown/fasthttp-reverse-proxy/debug.go:9:2: assignment mismatch: 1 variable but "github.com/yeqown/log".NewLogger returns 2 values

**Comment by yeqown** [comment]
Which version you are using? The master's latest?
