### ISSUE TITLE
error when proxying the request: HostClient can't follow redirects to a different protocol, please use Client instead

### ISSUE THREAD

**Issue by kotyara85** [yeqown/fasthttp-reverse-proxy#25]
I'm offloading tls on nginx ingress, so the traffic goes plain within k8s -> hits reverse proxy -> https to another resource.
Is there a way to make it work?
Thank you

**Comment by yeqown** [comment]
Could you provide any screenshots or logs? I could not understand the situation you had met. @kotyara85

**Comment by yeqown** [comment]
https://github.com/valyala/fasthttp/issues/841 may be helpful?
