### ISSUE TITLE
hostClient使用Pool好像最大连接数就失效了吧。

### ISSUE THREAD

**Issue by saltbo** [yeqown/fasthttp-reverse-proxy#6]
你好，本来我也是你这个思路。但是仔细想了下，他这个HostClient是host级别的，在它的内部维护了一个Host级别的最大连接数，所以，如果用对象池，他这个连接数就失效了。

**Comment by saltbo** [comment]
我现在也在纠结。用map就有性能问题，不用map又找不到其他什么好的办法。

而且，在微服务场景下，这个host的数量会特别多，限制单个host的连接数好像又没多大意义。

该怎么限制全局的连接数呢？

**Comment by saltbo** [comment]
@yeqown 有时间的话希望能进交流下想法

**Comment by yeqown** [comment]
@saltbo 我有点不明白：
reverse-proxy 在你的系统中的作用是什么呢？
你的需求就是想要限制全局的链接数么？

**Comment by saltbo** [comment]
我是在做API网关。以前用nethttp的时候他那个最大连接数是限制的全局的，现在不知道该怎么搞了。。

**Comment by yeqown** [comment]
有没有试过这个：
https://godoc.org/golang.org/x/net/netutil#LimitListener
