### ISSUE TITLE
Reverse proxy a Websocket server

### ISSUE THREAD

**Issue by na2axl** [yeqown/fasthttp-reverse-proxy#8]
Hi @yeqown and thank you for this helpful package.

I have a little issue, I want to reverse proxy a websocket server, but it seems to not working... Any tips or workaround to achieve this ? Thanks by advance....

For now, my code looks like this:
```go
package main

import (
	"log"
	"strings"

	"github.com/valyala/fasthttp"
	proxy "github.com/yeqown/fasthttp-reverse-proxy"
)

var (
	pool proxy.Pool
	err  error
)

// ProxyPoolHandler ...
func ProxyPoolHandler(ctx *fasthttp.RequestCtx) {
	path := string(ctx.Path())

	if strings.HasPrefix(path, "/api") {
		path = strings.TrimPrefix(path, "/api")

		var proxyServer *proxy.ReverseProxy

		switch true {
		case strings.HasPrefix(path, "/notifications/push"):
			proxyServer, err = pool.Get("127.0.0.1:8080")
			path = strings.TrimPrefix(path, "/notifications/push")
		case strings.HasPrefix(path, "/chat"):
			proxyServer, err = pool.Get("127.0.0.1:8081")
			path = strings.TrimPrefix(path, "/chat")
		}

		if proxyServer != nil {
			if err != nil {
				log.Println("ProxyPoolHandler got an error: ", err)
				ctx.SetStatusCode(fasthttp.StatusInternalServerError)
				return
			}

			ctx.Request.SetRequestURI(path)
			defer pool.Put(proxyServer)
			proxyServer.ServeHTTP(ctx)
		}
	} else {
		ctx.Response.SetBody([]byte("Not Found."))
	}
}

func factory(hostAddr string) (*proxy.ReverseProxy, error) {
	p := proxy.NewReverseProxy(hostAddr)
	return p, nil
}

func main() {
	initialCap, maxCap := 100, 200
	pool, err = proxy.NewChanPool(initialCap, maxCap, factory)
	if err := fasthttp.ListenAndServe(":80", ProxyPoolHandler); err != nil {
		panic(err)
	}
}
```

**Comment by yeqown** [comment]
I'm sorry to read this issue so late. did you find any way to achieve your goal? @na2axl

**Comment by yeqown** [comment]
I'll achieve this, refer to [koding/websocketprox](https://github.com/koding/websocketproxy)

**Comment by na2axl** [comment]
Hi @yeqown,

I've tried some things to get this working with my project, I've seen that request headers for WS connection are removed when proxying, so I've added it in WS server side before upgrade. With this I'm able to connect but the connection is closed immediatly (I think that is also because response headers for WS connection are also removed)...

I've also seen koding/websocketprox few days ago but is for golang net/http so I've never give a chance to it... :yum: 

Thanks in advance if you are searching a way to solve this!

**Comment by yeqown** [comment]
@na2axl 
I have achieved `Websocket` proxy in this repository, currently, code is on branch [feature/websocket-support](https://github.com/yeqown/fasthttp-reverse-proxy/blob/feature/websocket-support/examples/ws-fasthttp-reverse-proxy/ws_proxy.go), they are still not tested fully but may provide some help for you.

To achieve this quickly, I refer to two repo:
- [https://github.com/koding/websocketproxy](https://github.com/koding/websocketproxy)
- [https://github.com/fasthttp/websocket](https://github.com/fasthttp/websocket)

The second maybe helps you too.

**Comment by na2axl** [comment]
Thanks @yeqown, I will test it during the weekend!

**Comment by na2axl** [comment]
Hi @yeqown, your patch works correctly. For now I've found a little issue when a client try to close the WS connection itself.

On the proxy side, I got this message:
`websocketproxy: Error when copying from backend to client: websocket: close 1006 (abnormal closure): unexpected EOF`
But for the same closed connection, I got the right message on the WS backend server:
`websocket: close 1000 (normal): websocket: close 1005 (no status)`

Is this normal ?

**Comment by yeqown** [comment]
if you did the same action to close the client itself, the `CloseCode` should be same in my thought. However, I must learn more knowledge about `Websocket`, to find out what do those code means, when should they be used. 

Anyway, thanks for your testing 🔧

**Comment by yeqown** [comment]
@na2axl could you provide the code of how you close the client itself. I tried: Killing the client and

**Comment by na2axl** [comment]
Sorry @yeqown but I was using a WS test software (AdvancedRestClient) when reporting the error.

However, I've created a simple HTML file to test it with the browser, I'm gotting the same error. I've tried:

- Reload the page without disconnecting:
  - In the backend WS server log: `websocket: close 1001 (going away)`
  - In the proxy WS server log: `websocketproxy: Error when copying from backend to client: websocket: close 1006 (abnormal closure): unexpected EOF`
- Disconnect normally (calling `ws.close()` after a successful connection)
  - In the backend WS server log: `websocket: close 1000 (normal): websocket: close 1005 (no status)`
  - In the proxy WS server log: `websocketproxy: Error when copying from backend to client: websocket: close 1006 (abnormal closure): unexpected EOF`
- Create a connection using `new WebSocket(...)` and call `ws.close()` before the connection is made:
  - In the backend WS server log: `websocket: close 1001 (going away)`
  - In the proxy WS server log: `websocketproxy: Error when copying from backend to client: websocket: close 1006 (abnormal closure): unexpected EOF`

Notice that these logs appear simultaneously on two different CLI (one for the backend, another for the proxy). The code used for the proxy WS server is:

```golang
package main

import (
	"strings"

	"github.com/valyala/fasthttp"
	"github.com/fasthttp/websocket"
	proxy "github.com/yeqown/fasthttp-reverse-proxy"
)

var (
	err  error
)

func proxyHandler(ctx *fasthttp.RequestCtx) {
	path := string(ctx.Path())

	if strings.HasPrefix(path, "/api") {
		path = strings.TrimPrefix(path, "/api")

		var proxyServer *proxy.WSReverseProxy

		switch true {
		case strings.HasPrefix(path, "/notifications"):
			path = strings.TrimPrefix(path, "/notifications")
			proxyServer = proxy.NewWSReverseProxy("127.0.0.1:8080", path)
		case strings.HasPrefix(path, "/chat"):
			path = strings.TrimPrefix(path, "/chat")
			proxyServer = proxy.NewWSReverseProxy("127.0.0.1:8081", path)
		default:
			serve404(ctx);
		}

		if proxyServer != nil {
			ctx.Request.SetRequestURI(path)

			proxyServer.Upgrader = &websocket.FastHTTPUpgrader{
				CheckOrigin:     checkRequestOrigin,
				WriteBufferSize: 1024,
				ReadBufferSize:  1024,
			}

			proxyServer.ServeHTTP(ctx)
		}
	} else {
		serve404(ctx);
	}
}

func checkRequestOrigin(ctx *fasthttp.RequestCtx) bool {
	return true
}

func serve404(ctx *fasthttp.RequestCtx) {
	ctx.Response.SetStatusCode(404);
	ctx.Response.SetBody([]byte("Not Found."))
}

func main() {
	if err := fasthttp.ListenAndServe(":8083", proxyHandler); err != nil {
		panic(err)
	}
}
```

**Comment by yeqown** [comment]
@na2axl described so detailedly 👍 👍 👍 , I'll keep working on this issue and hope this would not bother you.
